apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: tools
  labels:
    app: grafana
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.10.10
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: grafana
  selector:
    app: grafana
